name: slack-backup

on:
  schedule:
    - cron:  '3 9 1 * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - id: logger
        uses: hiroshinomura/slack-backup@main
#        uses: kuboon/gsheet-slack-logger@main
        with:
          timezone: 'Asia/Tokyo'
          slackToken: ${{ secrets.SLACK_TOKEN }}
          googleClientEmail: slack-logger@gsheet-slack-logger-358003.iam.gserviceaccount.com
          googlePrivateKey: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          folderId: 1-ekgw05T8hgCWOvPlHOYemwrJEbRmPvM
          autoJoin: true
          skipChannels: ''
          year: 2022
          month: 5
          day: 1
